package com.example.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String, val flag: String) {
    ENGLISH("en", "English", "English", "🇬🇧"),
    HINDI("hi", "Hindi", "हिन्दी", "🇮🇳"),
    KANNADA("kn", "Kannada", "ಕನ್ನಡ", "🇮🇳"),
    MALAYALAM("ml", "Malayalam", "മലയാളം", "🇮🇳")
}

data class AppStrings(
    // App Bar & Top Header
    val appTitle: String = "TrustPay",
    val appName: String = "TrustPay",
    val tagline: String = "Payments that don't stop when the internet does.",
    val buyerRole: String = "Buyer",
    val merchantRole: String = "Merchant",
    val adminRole: String = "Admin",
    val continueText: String = "Continue",
    val buyerRolePrefix: String = "Buyer Terminal",
    val merchantRolePrefix: String = "Merchant Terminal",
    val adminRolePrefix: String = "Admin Terminal",
    val onlineStatus: String = "Online",
    val offlineStatus: String = "Offline",
    val liveSyncStatus: String = "Cloud Live",
    val offlineAllowanceBadge: String = "Offline Allowance Active",
    val offlineBannerNotice: String = "Offline Mode: Transactions are cryptographically signed on device and queued in local Room DB for zero-loss sync.",

    // Bottom Navigation
    val navHome: String = "Home",
    val navPay: String = "Pay",
    val navActivity: String = "Activity",
    val navSecurity: String = "Security",
    val navSettings: String = "Settings",
    val navTerminal: String = "Terminal",
    val navSync: String = "Sync",
    val navMonitor: String = "Monitor",
    val navAudit: String = "Audit",
    val navRecon: String = "Recon",

    // Buyer Home Screen
    val availableBalance: String = "Available Balance",
    val walletBalance: String = "Main Account Wallet",
    val walletBalanceLabel: String = "Main Account Wallet",
    val offlineExposure: String = "Offline Exposure",
    val offlineExposureLimit: String = "Bounded Limit",
    val exposurePercentage: String = "% of offline limit used",
    val makePayment: String = "Make Payment",
    val scanToPay: String = "Scan QR / Tap to Pay",
    val forceSync: String = "Sync Cloud",
    val recentTransactions: String = "Recent Transactions",
    val seeAll: String = "See all",
    val offlineSafeBadge: String = "Offline Protected",
    val cryptographicProofReady: String = "Ed25519 Signed",
    val noTransactionsYet: String = "No transactions found.",

    // Payment Screen
    val paymentTitle: String = "New Payment",
    val payOnlineTitle: String = "Pay Online",
    val payOfflineTitle: String = "Pay Offline",
    val scanQrOnline: String = "Scan QR",
    val upiIdMobile: String = "UPI ID / Mobile Number",
    val trustPayDirect: String = "TrustPay Payment",
    val scanOfflineQr: String = "Scan Offline QR",
    val offlineMethodQr: String = "QR Code",
    val offlineMethodBluetooth: String = "Bluetooth",
    val offlineMethodWifi: String = "Wi-Fi Direct",
    val offlineMethodUltrasonic: String = "Ultrasonic Wave",
    val payNearby: String = "Pay Nearby",
    val availableOfflineLimit: String = "Available Offline Limit",
    val willSettleWhenConnected: String = "Will settle when connection returns",
    val paymentAcceptedOffline: String = "Payment Accepted Offline",
    val paymentSettledOnline: String = "Payment Settled Online",
    val razorpayFlow: String = "Razorpay Flow",
    val trustAgentQuestion: String = "Can this transaction be accepted?",
    val yesAccepted: String = "YES: Within offline bounded limit",
    val signTransaction: String = "Sign transaction (Ed25519)",
    val pendingSync: String = "PENDING SYNC",
    val roomDbSaved: String = "Saved to Room DB",
    val selectMerchant: String = "Select Merchant",
    val selectMerchantPrompt: String = "Select Merchant",
    val enterAmount: String = "Enter Amount (₹)",
    val quickAmounts: String = "Quick Amounts",
    val paymentMode: String = "Payment Mode",
    val modeAutonomous: String = "Autonomous (TrustAgent)",
    val modeAutonomousDesc: String = "AI selects Offline Value or Mandate based on risk & connectivity",
    val modeMandate: String = "Autopay Mandate",
    val modeMandateDesc: String = "Direct debit authorization via bank mandate token",
    val modeOfflineValue: String = "Offline Value",
    val modeOfflineValueDesc: String = "Cryptographically signed peer-to-peer balance transfer",
    val trustDecisionTitle: String = "TrustAgent Decision",
    val riskScoreLabel: String = "Risk Probability",
    val confidenceLabel: String = "Confidence",
    val tamperSimulation: String = "Simulate Signature Tampering (Demo)",
    val tamperActiveWarning: String = "Tamper mode active: Will intentionally corrupt cryptographic signature to test audit rejection.",
    val payButton: String = "Pay ₹%s with TrustAgent",
    val signingInstruction: String = "Requires device private key signature",
    val paymentDeclinedTitle: String = "Transaction Declined",
    val paymentDeclinedMessage: String = "TrustAgent flagged this transaction due to risk constraints or exposure limit overruns.",

    // Confirmation Screen
    val paymentSuccessTitle: String = "Payment Authorized Offline",
    val paymentSuccessSubtitle: String = "Cryptographically signed with device private key and queued locally in Room DB.",
    val paymentDetails: String = "Payment Confirmation",
    val payToMerchant: String = "Paid to",
    val transactionDetails: String = "Transaction Details",
    val txId: String = "Transaction ID",
    val merchantLabel: String = "Merchant",
    val amountPaid: String = "Amount Paid",
    val modeLabel: String = "Mode",
    val statusLabel: String = "Status",
    val timestampLabel: String = "Timestamp",
    val cryptographicProof: String = "Cryptographic Proof",
    val publicKeyLabel: String = "Device Public Key",
    val signatureLabel: String = "Digital Signature (Ed25519)",
    val nonceLabel: String = "Anti-Replay Nonce",
    val payloadDigest: String = "Canonical Digest",
    val syncStatusLabel: String = "Sync Status",
    val queuedInRoom: String = "Queued in Local Room DB",
    val settledInCloud: String = "Settled in Supabase Cloud",
    val backToHome: String = "Back to Home",
    val triggerCloudSync: String = "Force Sync to Cloud",

    // Merchant Home Screen
    val terminalTitle: String = "Merchant POS Terminal",
    val merchantBalance: String = "Merchant Unsettled Receipts",
    val todayVolume: String = "Today's Volume",
    val dailyVolume: String = "Daily Volume",
    val incomingPaymentPrompt: String = "Scan QR or tap phone to accept peer-to-peer cryptographic payment",
    val acceptOfflinePayment: String = "Accept Offline Payment",
    val paymentSuccess: String = "Payment Success",
    val readyToScan: String = "Ready to Scan",
    val offlineVerificationNote: String = "Offline signatures are securely verified via local Ed25519 key validation",
    val pendingReconciliation: String = "Pending Reconciliation",
    val merchantTransactions: String = "Incoming Payments",
    val acceptPayment: String = "Accept & Verify Signature",
    val rejectPayment: String = "Reject",
    val signatureValid: String = "Signature Valid (Ed25519)",

    // Admin & Monitor Screen
    val adminTitle: String = "TrustPay Admin Monitor",
    val adminOverview: String = "Network Exposure & Forensic Monitor",
    val totalVolume: String = "Total Volume",
    val totalTransactions: String = "Total Transactions",
    val settledTransactions: String = "Settled Transactions",
    val pendingTransactions: String = "Pending Sync",
    val fraudTransactions: String = "Fraud Flags",
    val fraudRate: String = "Fraud Rate",
    val offlineTxLabel: String = "Offline Transactions",
    val activeAlerts: String = "Active Security Alerts",
    val securityAlerts: String = "Real-time Forensic Anomaly Alerts",
    val viewDetails: String = "View Forensic Details",

    // Activity & Sync Screen
    val activityTitle: String = "Reconciliation & Sync Ledger",
    val syncActivity: String = "Activity & Reconciliation",
    val syncNow: String = "Sync Cloud",
    val syncPipelineTitle: String = "15-Step Reconciliation Pipeline",
    val syncPipelineSubtitle: String = "Deterministic crypto verification, distributed replay check, ML fraud scoring, and Razorpay gateway settlement.",
    val startSyncButton: String = "Run 15-Step Cloud Sync",
    val allTransactionsHeader: String = "Transaction History",
    val filterAll: String = "All",
    val filterPending: String = "Pending",
    val filterSettled: String = "Settled",
    val filterFlagged: String = "Flagged",

    // Security Center Screen
    val securityCenter: String = "Security Center",
    val securityCenterTitle: String = "Forensic Security Center",
    val anomalyBreakdown: String = "ML Anomaly Scoring Breakdown",
    val isolationForestScore: String = "Isolation Forest Anomaly Score",
    val velocityScore: String = "Velocity Velocity Spike",
    val exposureRatio: String = "Offline Exposure Ratio",
    val syncDelayScore: String = "Sync Delay Anomaly",
    val askGeminiTitle: String = "Gemini Forensic Explainability",
    val askGeminiSubtitle: String = "Natural language explanation of why TrustAgent accepted or flagged this transaction.",
    val askGeminiButton: String = "Explain Transaction with Gemini",
    val restrictAccount: String = "Restrict Offline Spending",
    val accountRestricted: String = "Account is Restricted",
    val unrestrictAccount: String = "Lift Account Restriction",

    // Settings Screen
    val settingsTitle: String = "Settings & Preferences",
    val languageSection: String = "App Language",
    val selectLanguageSubtitle: String = "Choose your preferred interface and voice language",
    val themeModeSection: String = "Theme Appearance",
    val selectThemeSubtitle: String = "Switch between Light, Dark, or System Default appearance",
    val themeSystem: String = "System Default",
    val themeLight: String = "Light",
    val themeDark: String = "Dark",
    val voiceAssistantSection: String = "Multilingual Voice Assistant",
    val voiceAssistantSubtitle: String = "Speak naturally in English, Hindi, Kannada, or Malayalam",
    val launchVoiceAssistant: String = "Open Voice Assistant",
    val activePersona: String = "Active Persona",
    val connectionSimulation: String = "Connection Simulator",
    val backendStatus: String = "Backend & Cloud Ledger",
    val hackathonDemoTitle: String = "Showcase Demo Runner",
    val hackathonDemoSubtitle: String = "Executes automated end-to-end multi-step verification",
    val startDemoButton: String = "Start End-to-End Demo",
    val architecturePrinciples: String = "Core Architectural Principles",
    val deviceCryptography: String = "Device Cryptography & Keys",

    // Architectural Principles Bullets
    val archRule1: String = "Does not create an alternative currency or token",
    val archRule2: String = "Does not replace UPI; integrates with Razorpay Autopay",
    val archRule3: String = "Offline transactions labeled 'Offline Authorized', not settled",
    val archRule4: String = "Deterministic exposure limits (no AI for double-spend)",
    val archRule5: String = "Ed25519 asymmetric cryptographic signing",
    val archRule6: String = "Isolation Forest & XGBoost ML behavioral anomaly scoring",
    val archRule7: String = "Gemini AI explainability for compliance audit",

    // Backend Status & Ledger Settings
    val pendingRoomQueue: String = "Pending Room Queue",
    val lastSyncLabel: String = "Last Sync",
    val justNow: String = "Just now",
    val minutesAgo: String = "%dm ago",
    val notSyncedYet: String = "Not synced yet",
    val razorpayTargetLabel: String = "Razorpay Backend Proxy Target",
    val renderCloud: String = "Cloud Render",
    val localEmulator: String = "Local Emulator",
    val activeTargetPrefix: String = "Active Target",
    val liveSyncBadge: String = "LIVE SYNC",
    val roomOnlyBadge: String = "ROOM ONLY",
    val accountSessionTitle: String = "Account Session",
    val accountSessionDesc: String = "End your active session or switch to another user account. Returning will require logging in or choosing a demo role.",
    val logoutButtonLabel: String = "Logout / Switch Account",

    // Activity & Reconciliation Pipeline
    val transactionsDiscoveredLabel: String = "%d transactions discovered",
    val signaturesVerifiedLabel: String = "%d signatures verified",
    val replayAttacksLabel: String = "%d replay attacks",
    val duplicateTxLabel: String = "%d duplicate transactions",
    val highRiskFlaggedLabel: String = "%d high-risk transaction flagged",
    val lowRiskTxLabel: String = "%d low-risk transactions",
    val settlementSummaryTitle: String = "Settlement Summary",
    val settlementSummaryDesc: String = "%d successful, %d review required",
    val reviewFlaggedItemButton: String = "Review Flagged Item ->",

    // Security Center & Anomaly Investigation
    val anomalyInvestigationTitle: String = "Anomaly Investigation",
    val riskSpectrumTitle: String = "Risk Probability Spectrum",
    val riskSpectrumLow: String = "0% (Low)",
    val riskSpectrumMedium: String = "50% (Medium)",
    val riskSpectrumCritical: String = "100% (Critical)",
    val dualRiskAnalysisTitle: String = "Dual Risk Analysis Systems",
    val ruleBasedScoreTitle: String = "Rule-Based Risk Score",
    val ruleBasedScoreSubtitle: String = "Local Heuristic Engine (FraudDetector.kt)",
    val mlModelScoreTitle: String = "ML Model Risk Score",
    val mlModelScoreSubtitle: String = "Trained XGBoost model validated on synthetic data",
    val evaluatingText: String = "Evaluating...",
    val mlServiceUnavailable: String = "ML service unavailable — using local rules",
    val mlFallbackNotice: String = "Remote endpoint was unreachable or timed out. Honest fallback active: no score was fabricated.",
    val retryMlServiceButton: String = "Retry ML Service",
    val whyFlaggedTitle: String = "Why this was flagged",
    val investigateWithGeminiTitle: String = "Investigate with Gemini AI",
    val geminiModelSubtitle: String = "Model: gemini-2.5-flash • Explainability Only",
    val suggestedQuestionsTitle: String = "Suggested Questions:",
    val qWhyFlagged: String = "Why was this flagged?",
    val qIsDeviceCompromised: String = "Is device compromised?",
    val qRecommendedActions: String = "Recommended actions",

    // Payments
    val enterAmountOnlineDesc: String = "Enter Amount to send via Razorpay Flow",
    val enterAmountOfflineDesc: String = "Enter Amount to send via %s",

    // Voice Assistant
    val voiceListening: String = "Listening...",
    val voiceTapToSpeak: String = "Tap microphone to speak",
    val voiceTryAsking: String = "Try asking:",
    val voicePromptBalance: String = "What is my balance?",
    val voicePromptTransactions: String = "Show my recent transactions",
    val voicePromptSync: String = "Is sync pending?",
    val voicePromptPay: String = "Pay ₹200 to Artisan Roasters",
    val voicePromptSecurity: String = "Check my offline exposure",
    val voicePaymentNotice: String = "For security, voice commands cannot directly authorize payments. Navigating to payment screen for your verification.",
    val voiceSpeaking: String = "Speaking...",
    val voiceStopAudio: String = "Stop Audio",
    val voicePlayAudio: String = "Play Audio",
    val voiceClose: String = "Close",
    val voiceNotUnderstood: String = "Sorry, I didn't catch that. You can ask about balance, transactions, sync status, or say 'Pay ₹250 to Artisan Roasters'."
)


object LocalizationManager {
    fun getStrings(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.ENGLISH -> AppStrings()
            AppLanguage.HINDI -> AppStrings(
                appTitle = "ट्रस्टपे",
                buyerRolePrefix = "क्रेता: गणेश",
                merchantRolePrefix = "व्यापारी: आर्टिसन रोस्टर्स",
                adminRolePrefix = "व्यवस्थापक: सुरक्षा केंद्र",
                onlineStatus = "ऑनलाइन",
                offlineStatus = "ऑफलाइन",
                liveSyncStatus = "क्लाउड लाइव",
                offlineAllowanceBadge = "ऑफलाइन सीमा सक्रिय",
                offlineBannerNotice = "ऑफलाइन मोड: लेनदेन डिवाइस पर सुरक्षित रूप से हस्ताक्षरित हैं और शून्य-नुकसान सिंक के लिए रूम डेटाबेस में कतारबद्ध हैं।",

                navHome = "होम",
                navPay = "भुगतान",
                navActivity = "गतिविधि",
                navSecurity = "सुरक्षा",
                navSettings = "सेटिंग्स",
                navTerminal = "टर्मिनल",
                navSync = "सिंक",
                navMonitor = "निगरानी",
                navAudit = "ऑडिट",
                navRecon = "सुलह",

                availableBalance = "उपलब्ध बैलेंस",
                walletBalanceLabel = "मुख्य खाता वॉलेट",
                offlineExposure = "ऑफलाइन एक्सपोज़र",
                offlineExposureLimit = "निर्धारित सीमा",
                exposurePercentage = "% ऑफलाइन सीमा प्रयुक्त",
                makePayment = "भुगतान करें",
                scanToPay = "क्यूआर स्कैन / टैप करें",
                forceSync = "क्लाउड सिंक करें",
                recentTransactions = "हाल के लेनदेन",
                seeAll = "सभी देखें",
                offlineSafeBadge = "ऑफलाइन सुरक्षित",
                cryptographicProofReady = "Ed25519 हस्ताक्षरित",
                noTransactionsYet = "कोई लेनदेन नहीं मिला।",

                paymentTitle = "नया भुगतान",
                selectMerchant = "व्यापारी चुनें",
                enterAmount = "राशि दर्ज करें (₹)",
                quickAmounts = "त्वरित राशियां",
                paymentMode = "भुगतान मोड",
                modeAutonomous = "स्वायत्त (ट्रस्टएजेंट)",
                modeAutonomousDesc = "जोखिम और कनेक्टिविटी के आधार पर ऑफलाइन या मैंडेट चुनता है",
                modeMandate = "ऑटोपे मैंडेट",
                modeMandateDesc = "बैंक मैंडेट टोकन द्वारा प्रत्यक्ष डेबिट प्राधिकरण",
                modeOfflineValue = "ऑफलाइन मूल्य",
                modeOfflineValueDesc = "क्रिप्टोग्राफिक रूप से हस्ताक्षरित पीयर-टू-पीयर ट्रांसफर",
                trustDecisionTitle = "ट्रस्टएजेंट निर्णय",
                riskScoreLabel = "जोखिम संभावना",
                confidenceLabel = "विश्वास स्तर",
                tamperSimulation = "हस्ताक्षर छेड़छाड़ का अनुकरण (डेमो)",
                tamperActiveWarning = "छेड़छाड़ मोड सक्रिय: अस्वीकृति परीक्षण के लिए हस्ताक्षर जानबूझकर दूषित किए जाएंगे।",
                payButton = "ट्रस्टएजेंट से ₹%s का भुगतान करें",
                signingInstruction = "डिवाइस प्राइवेट की हस्ताक्षर आवश्यक है",
                paymentDeclinedTitle = "लेनदेन अस्वीकृत",
                paymentDeclinedMessage = "ट्रस्टएजेंट ने जोखिम सीमाओं या एक्सपोज़र के कारण इस लेनदेन को रोक दिया।",

                paymentSuccessTitle = "ऑफलाइन भुगतान अधिकृत",
                paymentSuccessSubtitle = "डिवाइस की से हस्ताक्षरित और स्थानीय रूम डेटाबेस में कतारबद्ध।",
                transactionDetails = "लेनदेन विवरण",
                txId = "लेनदेन आईडी",
                merchantLabel = "व्यापारी",
                amountPaid = "भुगतान राशि",
                modeLabel = "मोड",
                statusLabel = "स्थिति",
                timestampLabel = "समय",
                cryptographicProof = "क्रिप्टोग्राफिक प्रमाण",
                publicKeyLabel = "डिवाइस पब्लिक की",
                signatureLabel = "डिजिटल हस्ताक्षर (Ed25519)",
                nonceLabel = "एंटी-रीप्ले नॉनस",
                payloadDigest = "कैनोनिकल डाइजेस्ट",
                syncStatusLabel = "सिंक स्थिति",
                queuedInRoom = "लोकल रूम में कतारबद्ध",
                settledInCloud = "सुपाबेस क्लाउड में व्यवस्थित",
                backToHome = "होम पर लौटें",
                triggerCloudSync = "क्लाउड पर तुरंत सिंक करें",

                terminalTitle = "व्यापारी पीओएस टर्मिनल",
                merchantBalance = "असमायोजित प्राप्तियां",
                todayVolume = "आज का कुल योग",
                pendingReconciliation = "लंबित सुलह",
                merchantTransactions = "आवक भुगतान",
                acceptPayment = "स्वीकार करें व हस्ताक्षर जांचें",
                rejectPayment = "अस्वीकार करें",
                signatureValid = "हस्ताक्षर मान्य (Ed25519)",

                adminTitle = "ट्रस्टपे एडमिन मॉनिटर",
                totalVolume = "कुल लेनदेन राशि",
                totalTransactions = "कुल लेनदेन",
                settledTransactions = "निपटारे किए गए लेनदेन",
                pendingTransactions = "लंबित सिंक",
                fraudTransactions = "संदिग्ध अलर्ट",
                fraudRate = "धोखाधड़ी दर",
                offlineTxLabel = "ऑफलाइन लेनदेन",
                activeAlerts = "सक्रिय सुरक्षा अलर्ट",
                viewDetails = "फोरेंसिक विवरण देखें",

                activityTitle = "सुलह और सिंक लेजर",
                syncPipelineTitle = "15-चरणीय सुलह पाइपलाइन",
                syncPipelineSubtitle = "क्रिप्टो सत्यापन, रीप्ले जांच, एमएल फ्रॉड स्कोरिंग और रेज़रपे गेटवे निपटान।",
                startSyncButton = "15-चरणीय सिंक शुरू करें",
                allTransactionsHeader = "लेनदेन इतिहास",
                filterAll = "सभी",
                filterPending = "लंबित",
                filterSettled = "निपटाया गया",
                filterFlagged = "संदिग्ध",

                securityCenterTitle = "फोरेंसिक सुरक्षा केंद्र",
                anomalyBreakdown = "एमएल विसंगति स्कोर ब्रेकडाउन",
                isolationForestScore = "आइसोलेशन फॉरेस्ट विसंगति स्कोर",
                velocityScore = "लेनदेन वेग स्पाइक",
                exposureRatio = "ऑफलाइन एक्सपोज़र अनुपात",
                syncDelayScore = "सिंक विलंब विसंगति",
                askGeminiTitle = "जेमिनी फोरेंसिक व्याख्या",
                askGeminiSubtitle = "प्राकृतिक भाषा में समझें कि ट्रस्टएजेंट ने इसे क्यों स्वीकार या ध्वजांकित किया।",
                askGeminiButton = "जेमिनी से व्याख्या पूछें",
                restrictAccount = "ऑफलाइन खर्च प्रतिबंधित करें",
                accountRestricted = "खाता प्रतिबंधित है",
                unrestrictAccount = "प्रतिबंध हटाएं",

                settingsTitle = "सिस्टम सेटिंग्स और प्राथमिकताएं",
                languageSection = "ऐप भाषा",
                selectLanguageSubtitle = "अपनी पसंदीदा इंटरफ़ेस और वॉयस भाषा चुनें",
                themeModeSection = "थीम उपस्थिति",
                selectThemeSubtitle = "लाइट, डार्क या सिस्टम डिफॉल्ट थीम चुनें",
                themeSystem = "सिस्टम डिफ़ॉल्ट",
                themeLight = "लाइट",
                themeDark = "डार्क",
                voiceAssistantSection = "बहुभाषी वॉयस सहायक",
                voiceAssistantSubtitle = "अंग्रेजी, हिंदी, कन्नड़ या मलयालम में बोलें",
                launchVoiceAssistant = "वॉयस असिस्टेंट खोलें",
                activePersona = "सक्रिय व्यक्तित्व",
                connectionSimulation = "कनेक्शन सिम्युलेटर",
                backendStatus = "बैकएंड और क्लाउड लेजर",
                hackathonDemoTitle = "शोकेस डेमो रनर",
                hackathonDemoSubtitle = "स्वचालित एंड-टू-एंड बहु-चरणीय सत्यापन चलाता है",
                startDemoButton = "एंड-टू-एंड डेमो शुरू करें",
                architecturePrinciples = "मूल वास्तुकला सिद्धांत",
                deviceCryptography = "डिवाइस क्रिप्टोग्राफी और कीज़",

                voiceListening = "सुन रहा हूँ...",
                voiceTapToSpeak = "बोलने के लिए माइक दबाएं",
                voiceTryAsking = "यह पूछने का प्रयास करें:",
                voicePromptBalance = "मेरा बैलेंस क्या है?",
                voicePromptTransactions = "हाल के लेनदेन दिखाएं",
                voicePromptSync = "क्या सिंक लंबित है?",
                voicePromptPay = "आर्टिसन रोस्टर्स को ₹200 का भुगतान करें",
                voicePromptSecurity = "मेरा ऑफलाइन एक्सपोज़र जांचें",
                voicePaymentNotice = "सुरक्षा के लिए, वॉयस कमांड सीधे भुगतान अधिकृत नहीं कर सकते। आपके सत्यापन के लिए भुगतान स्क्रीन खोली जा रही है।",
                voiceSpeaking = "बोल रहा हूँ...",
                voiceStopAudio = "ऑडियो रोकें",
                voicePlayAudio = "ऑडियो सुनें",
                voiceClose = "बंद करें",
                voiceNotUnderstood = "क्षमा करें, मैं समझ नहीं पाया। आप बैलेंस, लेनदेन, सिंक स्थिति के बारे में पूछ सकते हैं।",

                archRule1 = "कोई वैकल्पिक मुद्रा या टोकन नहीं बनाता है",
                archRule2 = "यूपीआई को प्रतिस्थापित नहीं करता; रेजरपे ऑटोपे के साथ एकीकृत होता है",
                archRule3 = "ऑफलाइन लेनदेन 'ऑफलाइन अधिकृत' के रूप में चिह्नित होते हैं, निपटाए नहीं",
                archRule4 = "निर्धारित एक्सपोज़र सीमाएं (डबल-स्पेंड के लिए कोई एआई नहीं)",
                archRule5 = "Ed25519 एसिमेट्रिक क्रिप्टोग्राफिक हस्ताक्षर",
                archRule6 = "आइसोलेशन फॉरेस्ट और एक्सजीबूस्ट एमएल व्यवहारिक विसंगति स्कोरिंग",
                archRule7 = "अनुपालन ऑडिट के लिए जेमिनी एआई फोरेंसिक व्याख्या",

                pendingRoomQueue = "लंबित रूम कतार",
                lastSyncLabel = "अंतिम सिंक",
                justNow = "अभी-अभी",
                notSyncedYet = "अभी तक सिंक नहीं हुआ",
                razorpayTargetLabel = "रेजरपे बैकएंड प्रॉक्सी लक्ष्य",
                renderCloud = "क्लाउड रेंडर",
                localEmulator = "स्थानीय एमुलेटर",
                accountSessionTitle = "खाता सत्र",
                accountSessionDesc = "अपना सक्रिय सत्र समाप्त करें या किसी अन्य उपयोगकर्ता खाते में स्विच करें।",
                logoutButtonLabel = "लॉगआउट / खाता बदलें",

                transactionsDiscoveredLabel = "%d लेनदेन मिले",
                signaturesVerifiedLabel = "%d हस्ताक्षर सत्यापित",
                replayAttacksLabel = "%d रीप्ले हमले",
                duplicateTxLabel = "%d डुप्लिकेट लेनदेन",
                highRiskFlaggedLabel = "%d उच्च-जोखिम वाले लेनदेन ध्वजांकित",
                lowRiskTxLabel = "%d कम-जोखिम वाले लेनदेन",
                settlementSummaryTitle = "निपटान सारांश",
                settlementSummaryDesc = "%d सफल, %d समीक्षा आवश्यक",
                reviewFlaggedItemButton = "ध्वजांकित आइटम की समीक्षा करें ->",

                anomalyInvestigationTitle = "विसंगति जांच",
                riskSpectrumTitle = "जोखिम संभावना स्पेक्ट्रम",
                riskSpectrumLow = "0% (कम)",
                riskSpectrumMedium = "50% (मध्यम)",
                riskSpectrumCritical = "100% (गंभीर)",
                dualRiskAnalysisTitle = "द्वंद्व जोखिम विश्लेषण प्रणाली",
                ruleBasedScoreTitle = "नियम-आधारित जोखिम स्कोर",
                ruleBasedScoreSubtitle = "स्थानीय ह्यूरिस्टिक इंजन (FraudDetector.kt)",
                mlModelScoreTitle = "एमएल मॉडल जोखिम स्कोर",
                mlModelScoreSubtitle = "प्रशिक्षित एक्सजीबूस्ट मॉडल द्वारा सत्यापित",
                evaluatingText = "मूल्यांकन हो रहा है...",
                mlServiceUnavailable = "एमएल सेवा अनुपलब्ध — स्थानीय नियमों का उपयोग",
                mlFallbackNotice = "रिमोट एंडपॉइंट अनुपलब्ध था या टाइमआउट हो गया। ईमानदार फॉलबैक सक्रिय है।",
                retryMlServiceButton = "एमएल सेवा पुनः प्रयास करें",
                whyFlaggedTitle = "इसे क्यों ध्वजांकित किया गया",
                investigateWithGeminiTitle = "जेमिनी एआई के साथ जांच करें",
                geminiModelSubtitle = "मॉडल: gemini-2.5-flash • केवल व्याख्या",
                suggestedQuestionsTitle = "सुझाए गए प्रश्न:",
                qWhyFlagged = "इसे क्यों ध्वजांकित किया गया?",
                qIsDeviceCompromised = "क्या डिवाइस असुरक्षित है?",
                qRecommendedActions = "अनुशंसित कार्रवाइयां",

                enterAmountOnlineDesc = "रेजरपे फ्लो के माध्यम से भेजने के लिए राशि दर्ज करें",
                enterAmountOfflineDesc = "%s के माध्यम से भेजने के लिए राशि दर्ज करें"
            )


            AppLanguage.KANNADA -> AppStrings(
                appTitle = "ಟ್ರಸ್ಟ್‌ಪೇ",
                buyerRolePrefix = "ಖರೀದಿದಾರ: ಗಣೇಶ್",
                merchantRolePrefix = "ವ್ಯಾಪಾರಿ: ಆರ್ಟಿಸನ್ ರೋಸ್ಟರ್ಸ್",
                adminRolePrefix = "ನಿರ್ವಾಹಕ: ಭದ್ರತಾ ಕೇಂದ್ರ",
                onlineStatus = "ಆನ್‌ಲೈನ್",
                offlineStatus = "ಆಫ್‌ಲೈನ್",
                liveSyncStatus = "ಕ್ಲೌಡ್ ಲೈವ್",
                offlineAllowanceBadge = "ಆಫ್‌ಲೈನ್ ಮಿತಿ ಸಕ್ರಿಯ",
                offlineBannerNotice = "ಆಫ್‌ಲೈನ್ ಮೋಡ್: ವಹಿವಾಟುಗಳು ಸಾಧನದಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿ ಸಹಿ ಮಾಡಲ್ಪಟ್ಟಿವೆ ಮತ್ತು ನಷ್ಟವಿಲ್ಲದ ಸಿಂಕ್‌ಗಾಗಿ ರೂಮ್ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",

                navHome = "ಮುಖಪುಟ",
                navPay = "ಪಾವತಿ",
                navActivity = "ಚಟುವಟಿಕೆ",
                navSecurity = "ಭದ್ರತೆ",
                navSettings = "ಸೆಟ್ಟಿಂಗ್ಸ್",
                navTerminal = "ಟರ್ಮಿನಲ್",
                navSync = "ಸಿಂಕ್",
                navMonitor = "ಮೇಲ್ವಿಚಾರಣೆ",
                navAudit = "ಆಡಿಟ್",
                navRecon = "ಹೊಂದಾಣಿಕೆ",

                availableBalance = "ಲಭ್ಯವಿರುವ ಬಾಕಿ",
                walletBalanceLabel = "ಮುಖ್ಯ ಖಾತೆ ವ್ಯಾಲೆಟ್",
                offlineExposure = "ಆಫ್‌ಲೈನ್ ಎಕ್ಸ್‌ಪೋಸರ್",
                offlineExposureLimit = "ಗರಿಷ್ಠ ಮಿತಿ",
                exposurePercentage = "% ಆಫ್‌ಲೈನ್ ಮಿತಿ ಬಳಸಲಾಗಿದೆ",
                makePayment = "ಪಾವತಿ ಮಾಡಿ",
                scanToPay = "ಸ್ಕ್ಯಾನ್ / ಟ್ಯಾಪ್ ಮಾಡಿ",
                forceSync = "ಕ್ಲೌಡ್ ಸಿಂಕ್ ಮಾಡಿ",
                recentTransactions = "ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು",
                seeAll = "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",
                offlineSafeBadge = "ಆಫ್‌ಲೈನ್ ಸುರಕ್ಷಿತ",
                cryptographicProofReady = "Ed25519 ಸಹಿ ಮಾಡಲಾಗಿದೆ",
                noTransactionsYet = "ಯಾವುದೇ ವಹಿವಾಟುಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",

                paymentTitle = "ಹೊಸ ಪಾವತಿ",
                selectMerchant = "ವ್ಯಾಪಾರಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
                enterAmount = "ಮೊತ್ತ ನಮೂದಿಸಿ (₹)",
                quickAmounts = "ತ್ವರಿತ ಮೊತ್ತಗಳು",
                paymentMode = "ಪಾವತಿ ಮೋಡ್",
                modeAutonomous = "ಸ್ವಾಯತ್ತ (ಟ್ರಸ್ಟ್‌ಏಜೆಂಟ್)",
                modeAutonomousDesc = "ಅಪಾಯ ಮತ್ತು ಸಂಪರ್ಕದ ಆಧಾರದ ಮೇಲೆ ಸೂಕ್ತ ಮೋಡ್ ಆಯ್ಕೆಮಾಡುತ್ತದೆ",
                modeMandate = "ಆಟೋಪೇ ಮ್ಯಾಂಡೇಟ್",
                modeMandateDesc = "ಬ್ಯಾಂಕ್ ಮ್ಯಾಂಡೇಟ್ ಟೋಕನ್ ಮೂಲಕ ನೇರ ಡೆಬಿಟ್ ದೃಢೀಕರಣ",
                modeOfflineValue = "ಆಫ್‌ಲೈನ್ ಮೌಲ್ಯ",
                modeOfflineValueDesc = "ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಸಹಿ ಹೊಂದಿರುವ ಪೀರ್-ಟು-ಪೀರ್ ವರ್ಗಾವಣೆ",
                trustDecisionTitle = "ಟ್ರಸ್ಟ್‌ಏಜೆಂಟ್ ನಿರ್ಧಾರ",
                riskScoreLabel = "ಅಪಾಯದ ಸಂಭವನೀಯತೆ",
                confidenceLabel = "ವಿಶ್ವಾಸಾರ್ಹತೆ",
                tamperSimulation = "ಸಹಿ ತಿರುಚುವಿಕೆ ಪರೀಕ್ಷೆ (ಡೆಮೊ)",
                tamperActiveWarning = "ತಿರುಚುವಿಕೆ ಮೋಡ್ ಸಕ್ರಿಯವಾಗಿದೆ: ನಿರಾಕರಣೆಯನ್ನು ಪರೀಕ್ಷಿಸಲು ಸಹಿಯನ್ನು ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಹಾಳುಮಾಡಲಾಗುತ್ತದೆ.",
                payButton = "ಟ್ರಸ್ಟ್‌ಏಜೆಂಟ್ ಮೂಲಕ ₹%s ಪಾವತಿಸಿ",
                signingInstruction = "ಸಾಧನದ ಖಾಸಗಿ ಕೀಲಿ ಸಹಿ ಅಗತ್ಯವಿದೆ",
                paymentDeclinedTitle = "ವಹಿವಾಟು ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
                paymentDeclinedMessage = "ಅಪಾಯ ಅಥವಾ ಎಕ್ಸ್‌ಪೋಸರ್ ಮಿತಿಯನ್ನು ಮೀರಿದ್ದರಿಂದ ಟ್ರಸ್ಟ್‌ಏಜೆಂಟ್ ಈ ವಹಿವಾಟನ್ನು ನಿರ್ಬಂಧಿಸಿದೆ.",

                paymentSuccessTitle = "ಆಫ್‌ಲೈನ್ ಪಾವತಿ ದೃಢೀಕರಿಸಲಾಗಿದೆ",
                paymentSuccessSubtitle = "ಸಾಧನದ ಕೀಲಿಯೊಂದಿಗೆ ಸಹಿ ಮಾಡಲಾಗಿದೆ ಮತ್ತು ಸ್ಥಳೀಯ ರೂಮ್ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ.",
                transactionDetails = "ವಹಿವಾಟಿನ ವಿವರಗಳು",
                txId = "ವಹಿವಾಟು ಐಡಿ",
                merchantLabel = "ವ್ಯಾಪಾರಿ",
                amountPaid = "ಪಾವತಿಸಿದ ಮೊತ್ತ",
                modeLabel = "ಮೋಡ್",
                statusLabel = "ಸ್ಥಿತಿ",
                timestampLabel = "ಸಮಯ",
                cryptographicProof = "ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಪುರಾವೆ",
                publicKeyLabel = "ಸಾಧನದ ಸಾರ್ವಜನಿಕ ಕೀಲಿ",
                signatureLabel = "ಡಿಜಿಟಲ್ ಸಹಿ (Ed25519)",
                nonceLabel = "ಆಂಟಿ-ರಿಪ್ಲೇ ನಾನ್ಸ್",
                payloadDigest = "ಕ್ಯಾನೊನಿಕಲ್ ಡೈಜೆಸ್ಟ್",
                syncStatusLabel = "ಸಿಂಕ್ ಸ್ಥಿತಿ",
                queuedInRoom = "ರೂಮ್‌ನಲ್ಲಿ ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ",
                settledInCloud = "ಸುಪಬೇಸ್ ಕ್ಲೌಡ್‌ನಲ್ಲಿ ಇತ್ಯರ್ಥಗೊಂಡಿದೆ",
                backToHome = "ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
                triggerCloudSync = "ಕ್ಲೌಡ್‌ಗೆ ತಕ್ಷಣ ಸಿಂಕ್ ಮಾಡಿ",

                terminalTitle = "ವ್ಯಾಪಾರಿ ಪಿಒಎಸ್ ಟರ್ಮಿನಲ್",
                merchantBalance = "ಇತ್ಯರ್ಥವಾಗದ ರಶೀದಿಗಳು",
                todayVolume = "ಇಂದಿನ ಒಟ್ಟು ಮೊತ್ತ",
                pendingReconciliation = "ಬಾಕಿ ಉಳಿದ ಹೊಂದಾಣಿಕೆ",
                merchantTransactions = "ಬಂದ ಪಾವತಿಗಳು",
                acceptPayment = "ಸ್ವೀಕರಿಸಿ ಮತ್ತು ಸಹಿ ಪರಿಶೀಲಿಸಿ",
                rejectPayment = "ತಿರಸ್ಕರಿಸಿ",
                signatureValid = "ಸಹಿ ಮಾನ್ಯವಾಗಿದೆ (Ed25519)",

                adminTitle = "ಟ್ರಸ್ಟ್‌ಪೇ ನಿರ್ವಾಹಕ ಮಾನಿಟರ್",
                totalVolume = "ಒಟ್ಟು ವಹಿವಾಟು ಮೊತ್ತ",
                totalTransactions = "ಒಟ್ಟು ವಹಿವಾಟುಗಳು",
                settledTransactions = "ಇತ್ಯರ್ಥವಾದ ವಹಿವಾಟುಗಳು",
                pendingTransactions = "ಬಾಕಿ ಸಿಂಕ್",
                fraudTransactions = "ವಂಚನೆ ಎಚ್ಚರಿಕೆಗಳು",
                fraudRate = "ವಂಚನೆ ದರ",
                offlineTxLabel = "ಆಫ್‌ಲೈನ್ ವಹಿವಾಟುಗಳು",
                activeAlerts = "ಸಕ್ರಿಯ ಭದ್ರತಾ ಎಚ್ಚರಿಕೆಗಳು",
                viewDetails = "ವಿಧಿವಿಜ್ಞಾನ ವಿವರಗಳನ್ನು ನೋಡಿ",

                activityTitle = "ಹೊಂದಾಣಿಕೆ ಮತ್ತು ಸಿಂಕ್ ಲೆಡ್ಜರ್",
                syncPipelineTitle = "15-ಹಂತದ ಹೊಂದಾಣಿಕೆ ಪೈಪ್‌ಲೈನ್",
                syncPipelineSubtitle = "ಕ್ರಿಪ್ಟೋ ಪರಿಶೀಲನೆ, ರಿಪ್ಲೇ ತಪಾಸಣೆ, ಎಂಎಲ್ ವಂಚನೆ ಸ್ಕೋರಿಂಗ್ ಮತ್ತು ರೇಜರ್‌ಪೇ ಗೇಟ್‌ವೇ ಇತ್ಯರ್ಥ.",
                startSyncButton = "15-ಹಂತದ ಸಿಂಕ್ ರನ್ ಮಾಡಿ",
                allTransactionsHeader = "ವಹಿವಾಟು ಇತಿಹಾಸ",
                filterAll = "ಎಲ್ಲಾ",
                filterPending = "ಬಾಕಿ",
                filterSettled = "ಇತ್ಯರ್ಥವಾಗಿದೆ",
                filterFlagged = "ಎಚ್ಚರಿಕೆ",

                securityCenterTitle = "ವಿಧಿವಿಜ್ಞಾನ ಭದ್ರತಾ ಕೇಂದ್ರ",
                anomalyBreakdown = "ಎಂಎಲ್ ಅಸಂಗತತೆ ಸ್ಕೋರ್ ವಿವರ",
                isolationForestScore = "ಐಸೋಲೇಷನ್ ಫಾರೆಸ್ಟ್ ಅಸಂಗತತೆ ಸ್ಕೋರ್",
                velocityScore = "ವಹಿವಾಟು ವೇಗದ ಸ್ಪೈಕ್",
                exposureRatio = "ಆಫ್‌ಲೈನ್ ಎಕ್ಸ್‌ಪೋಸರ್ ಅನುಪಾತ",
                syncDelayScore = "ಸಿಂಕ್ ವಿಳಂಬ ಅಸಂಗತತೆ",
                askGeminiTitle = "ಜೆಮಿನಿ ವಿಧಿವಿಜ್ಞಾನ ವಿವರಣೆ",
                askGeminiSubtitle = "ಟ್ರಸ್ಟ್‌ಏಜೆಂಟ್ ಇದನ್ನು ಏಕೆ ಸ್ವೀಕರಿಸಿದೆ ಅಥವಾ ಫ್ಲ್ಯಾಗ್ ಮಾಡಿದೆ ಎಂಬುದನ್ನು ಸರಳವಾಗಿ ತಿಳಿಯಿರಿ.",
                askGeminiButton = "ಜೆಮಿನಿಯಿಂದ ವಿವರಣೆ ಪಡೆಯಿರಿ",
                restrictAccount = "ಆಫ್‌ಲೈನ್ ಖರ್ಚು ನಿರ್ಬಂಧಿಸಿ",
                accountRestricted = "ಖಾತೆಯನ್ನು ನಿರ್ಬಂಧಿಸಲಾಗಿದೆ",
                unrestrictAccount = "ನಿರ್ಬಂಧವನ್ನು ತೆರವುಗೊಳಿಸಿ",

                settingsTitle = "ಸಿಸ್ಟಂ ಸೆಟ್ಟಿಂಗ್ಸ್ ಮತ್ತು ಆದ್ಯತೆಗಳು",
                languageSection = "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ",
                selectLanguageSubtitle = "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಇಂಟರ್ಫೇಸ್ ಮತ್ತು ಧ್ವನಿ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
                themeModeSection = "ಥೀಮ್ ನೋಟ",
                selectThemeSubtitle = "ಲೈಟ್, ಡಾರ್ಕ್ ಅಥವಾ ಸಿಸ್ಟಂ ಡೀಫಾಲ್ಟ್ ನೋಟವನ್ನು ಆರಿಸಿ",
                themeSystem = "ಸಿಸ್ಟಂ ಡೀಫಾಲ್ಟ್",
                themeLight = "ಲೈಟ್",
                themeDark = "ಡಾರ್ಕ್",
                voiceAssistantSection = "ಬಹುಭಾಷಾ ಧ್ವನಿ ಸಹಾಯಕ",
                voiceAssistantSubtitle = "ಇಂಗ್ಲಿಷ್, ಹಿಂದಿ, ಕನ್ನಡ ಅಥವಾ ಮಲಯಾಳಂನಲ್ಲಿ ಮಾತನಾಡಿ",
                launchVoiceAssistant = "ಧ್ವನಿ ಸಹಾಯಕ ತೆರೆಯಿರಿ",
                activePersona = "ಸಕ್ರಿಯ ಪಾತ್ರ",
                connectionSimulation = "ಸಂಪರ್ಕ ಸಿಮ್ಯುಲೇಟರ್",
                backendStatus = "ಬ್ಯಾಕೆಂಡ್ ಮತ್ತು ಕ್ಲೌಡ್ ಲೆಡ್ಜರ್",
                hackathonDemoTitle = "ಶೋಕೇಸ್ ಡೆಮೊ ರನ್ನರ್",
                hackathonDemoSubtitle = "ಸ್ವಯಂಚಾಲಿತ ಹಂತ-ಹಂತದ ಪರಿಶೀಲನೆಯನ್ನು ನಡೆಸುತ್ತದೆ",
                startDemoButton = "ಸಂಪೂರ್ಣ ಡೆಮೊ ಪ್ರಾರಂಭಿಸಿ",
                architecturePrinciples = "ಮೂಲ ವಾಸ್ತುಶಿಲ್ಪ ತತ್ವಗಳು",
                deviceCryptography = "ಸಾಧನ ಕ್ರಿಪ್ಟೋಗ್ರಫಿ ಮತ್ತು ಕೀಲಿಗಳು",

                voiceListening = "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದೇನೆ...",
                voiceTapToSpeak = "ಮಾತನಾಡಲು ಮೈಕ್ರೊಫೋನ್ ಸ್ಪರ್ಶಿಸಿ",
                voiceTryAsking = "ಹೀಗೆ ಕೇಳಿ ನೋಡಿ:",
                voicePromptBalance = "ನನ್ನ ಬ್ಯಾಲೆನ್ಸ್ ಎಷ್ಟು?",
                voicePromptTransactions = "ನನ್ನ ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳನ್ನು ತೋರಿಸಿ",
                voicePromptSync = "ಸಿಂಕ್ ಬಾಕಿ ಇದೆಯೇ?",
                voicePromptPay = "ಆರ್ಟಿಸನ್ ರೋಸ್ಟರ್ಸ್‌ಗೆ ₹200 ಪಾವತಿಸಿ",
                voicePromptSecurity = "ನನ್ನ ಆಫ್‌ಲೈನ್ ಎಕ್ಸ್‌ಪೋಸರ್ ಪರಿಶೀಲಿಸಿ",
                voicePaymentNotice = "ಭದ್ರತಾ ಕಾರಣಗಳಿಗಾಗಿ, ಧ್ವನಿ ಆಜ್ಞೆಗಳು ನೇರವಾಗಿ ಪಾವತಿಯನ್ನು ಅಧಿಕೃತಗೊಳಿಸುವುದಿಲ್ಲ. ನಿಮ್ಮ ಪರಿಶೀಲನೆಗಾಗಿ ಪಾವತಿ ಪರದೆಗೆ ಹೋಗಲಾಗುತ್ತಿದೆ.",
                voiceSpeaking = "ಮಾತನಾಡುತ್ತಿದ್ದೇನೆ...",
                voiceStopAudio = "ಆಡಿಯೋ ನಿಲ್ಲಿಸಿ",
                voicePlayAudio = "ಆಡಿಯೋ ಪ್ಲೇ ಮಾಡಿ",
                voiceClose = "ಮುಚ್ಚಿ",
                voiceNotUnderstood = "ಕ್ಷಮಿಸಿ, ಅರ್ಥವಾಗಲಿಲ್ಲ. ನೀವು ಬ್ಯಾಲೆನ್ಸ್, ವಹಿವಾಟುಗಳು, ಸಿಂಕ್ ಸ್ಥಿತಿಯ ಬಗ್ಗೆ ಕೇಳಬಹುದು.",

                archRule1 = "ಯಾವುದೇ ಪರ್ಯಾಯ ಕರೆನ್ಸಿ ಅಥವಾ ಟೋಕನ್ ರಚಿಸುವುದಿಲ್ಲ",
                archRule2 = "ಯುಪಿಐ ಬದಲಾಯಿಸುವುದಿಲ್ಲ; ರೇಜರ್‌ಪೇ ಆಟೋಪೇ ಜೊತೆಗೆ ಸಂಯೋಜನೆಗೊಳ್ಳುತ್ತದೆ",
                archRule3 = "ಆಫ್‌ಲೈನ್ ವಹಿವಾಟುಗಳನ್ನು 'ಆಫ್‌ಲೈನ್ ಅಧಿಕೃತ' ಎಂದು ಗುರುತಿಸಲಾಗುತ್ತದೆ, ಇತ್ಯರ್ಥವಾಗಿಲ್ಲ",
                archRule4 = "ನಿರ್ದಿಷ್ಟ ಎಕ್ಸ್‌ಪೋಸರ್ ಮಿತಿಗಳು (ಡಬಲ್-ಸ್ಪೆಂಡ್‌ಗೆ ಯಾವುದೇ ಎಐ ಇಲ್ಲ)",
                archRule5 = "Ed25519 ಅಸಮಪಾರ್ಶ್ವದ ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಸಹಿ",
                archRule6 = "ಐಸೋಲೇಷನ್ ಫಾರೆಸ್ಟ್ ಮತ್ತು ಎಕ್ಸ್‌ಜಿಬೂಸ್ಟ್ ಎಂಎಲ್ ನಡವಳಿಕೆಯ ಸ್ಕೋರಿಂಗ್",
                archRule7 = "ಅನುಸರಣೆ ಆಡಿಟ್‌ಗಾಗಿ ಜೆಮಿನಿ ಎಐ ವಿವರಣೆ",

                pendingRoomQueue = "ಬಾಕಿ ಉಳಿದ ರೂಮ್ ಕ್ಯೂ",
                lastSyncLabel = "ಕೊನೆಯ ಸಿಂಕ್",
                justNow = "ಈಗಷ್ಟೇ",
                notSyncedYet = "ಇನ್ನೂ ಸಿಂಕ್ ಆಗಿಲ್ಲ",
                razorpayTargetLabel = "ರೇಜರ್‌ಪೇ ಬ್ಯಾಕೆಂಡ್ ಪ್ರಾಕ್ಸಿ ಟಾರ್ಗೆಟ್",
                renderCloud = "ಕ್ಲೌಡ್ ರೆಂಡರ್",
                localEmulator = "ಸ್ಥಳೀಯ ಎಮ್ಯುಲೇಟರ್",
                accountSessionTitle = "ಖಾತೆ ಸೆಷನ್",
                accountSessionDesc = "ನಿಮ್ಮ ಸಕ್ರಿಯ ಸೆಷನ್ ಕೊನೆಗೊಳಿಸಿ ಅಥವಾ ಇನ್ನೊಂದು ಬಳಕೆದಾರ ಖಾತೆಗೆ ಬದಲಾಯಿಸಿ.",
                logoutButtonLabel = "ಲಾಗ್‌ಔಟ್ / ಖಾತೆ ಬದಲಾಯಿಸಿ",

                transactionsDiscoveredLabel = "%d ವಹಿವಾಟುಗಳು ಕಂಡುಬಂದಿವೆ",
                signaturesVerifiedLabel = "%d ಸಹಿಗಳು ಪರಿಶೀಲಿಸಲ್ಪಟ್ಟಿವೆ",
                replayAttacksLabel = "%d ರಿಪ್ಲೇ ದಾಳಿಗಳು",
                duplicateTxLabel = "%d ನಕಲಿ ವಹಿವಾಟುಗಳು",
                highRiskFlaggedLabel = "%d ಹೆಚ್ಚಿನ ಅಪಾಯದ ವಹಿವಾಟು ಗುರುತಿಸಲಾಗಿದೆ",
                lowRiskTxLabel = "%d ಕಡಿಮೆ ಅಪಾಯದ ವಹಿವಾಟುಗಳು",
                settlementSummaryTitle = "ಇತ್ಯರ್ಥ ಸಾರಾಂಶ",
                settlementSummaryDesc = "%d ಯಶಸ್ವಿ, %d ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ",
                reviewFlaggedItemButton = "ಗುರುತಿಸಲಾದ ವಹಿವಾಟು ಪರಿಶೀಲಿಸಿ ->",

                anomalyInvestigationTitle = "ಅಸಂಗತತೆ ತನಿಖೆ",
                riskSpectrumTitle = "ಅಪಾಯದ ಸಂಭವನೀಯತೆಯ ಶ್ರೇಣಿ",
                riskSpectrumLow = "0% (ಕಡಿಮೆ)",
                riskSpectrumMedium = "50% (ಮಧ್ಯಮ)",
                riskSpectrumCritical = "100% (ಗಂಭೀರ)",
                dualRiskAnalysisTitle = "ದ್ವಿಮುಖ ಅಪಾಯ ವಿಶ್ಲೇಷಣೆ ವ್ಯವಸ್ಥೆ",
                ruleBasedScoreTitle = "ನಿಯಮ ಆಧಾರಿತ ಅಪಾಯ ಸ್ಕೋರ್",
                ruleBasedScoreSubtitle = "ಸ್ಥಳೀಯ ನಿಯಮಗಳ ಇಂಜಿನ್ (FraudDetector.kt)",
                mlModelScoreTitle = "ಎಂಎಲ್ ಮಾಡೆಲ್ ಅಪಾಯ ಸ್ಕೋರ್",
                mlModelScoreSubtitle = "ತರಬೇತಿ ಪಡೆದ ಎಕ್ಸ್‌ಜಿಬೂಸ್ಟ್ ಮಾಡೆಲ್ ಮೂಲಕ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
                evaluatingText = "ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗುತ್ತಿದೆ...",
                mlServiceUnavailable = "ಎಂಎಲ್ ಸೇವೆ ಲಭ್ಯವಿಲ್ಲ — ಸ್ಥಳೀಯ ನಿಯಮಗಳನ್ನು ಬಳಸಲಾಗುತ್ತಿದೆ",
                mlFallbackNotice = "ರಿಮೋಟ್ ಎಂಡ್ ಪಾಯಿಂಟ್ ಲಭ್ಯವಿರಲಿಲ್ಲ ಅಥವಾ ಸಮಯ ಮುಗಿಯಿತು.",
                retryMlServiceButton = "ಎಂಎಲ್ ಸೇವೆ ಮರುಪ್ರಯತ್ನಿಸಿ",
                whyFlaggedTitle = "ಇದನ್ನು ಏಕೆ ಗುರುತಿಸಲಾಗಿದೆ",
                investigateWithGeminiTitle = "ಜೆಮಿನಿ ಎಐ ಜೊತೆ ತನಿಖೆ ಮಾಡಿ",
                geminiModelSubtitle = "ಮಾಡೆಲ್: gemini-2.5-flash • ವಿವರಣೆ ಮಾತ್ರ",
                suggestedQuestionsTitle = "ಸೂಚಿಸಲಾದ ಪ್ರಶ್ನೆಗಳು:",
                qWhyFlagged = "ಇದನ್ನು ಏಕೆ ಗುರುತಿಸಲಾಗಿದೆ?",
                qIsDeviceCompromised = "ಸಾಧನವು ಅಪಾಯದಲ್ಲಿದೆಯೇ?",
                qRecommendedActions = "ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮಗಳು",

                enterAmountOnlineDesc = "ರೇಜರ್‌ಪೇ ಫ್ಲೋ ಮೂಲಕ ಕಳುಹಿಸಲು ಮೊತ್ತ ನಮೂದಿಸಿ",
                enterAmountOfflineDesc = "%s ಮೂಲಕ ಕಳುಹಿಸಲು ಮೊತ್ತ ನಮೂದಿಸಿ"
            )


            AppLanguage.MALAYALAM -> AppStrings(
                appTitle = "ട്രസ്റ്റ്പേ",
                buyerRolePrefix = "ഉപഭോക്താവ്: ഗണേഷ്",
                merchantRolePrefix = "വ്യാപാരി: ആർട്ടിസാൻ റോസ്റ്റേഴ്സ്",
                adminRolePrefix = "അഡ്മിൻ: സുരക്ഷാ കേന്ദ്രം",
                onlineStatus = "ഓൺലൈൻ",
                offlineStatus = "ഓഫ്‌ലൈൻ",
                liveSyncStatus = "ക്ലൗഡ് ലൈവ്",
                offlineAllowanceBadge = "ഓഫ്‌ലൈൻ പരിധി സജീവം",
                offlineBannerNotice = "ഓഫ്‌ലൈൻ മോഡ്: ഇടപാടുകൾ ഉപകരണത്തിൽ സുരക്ഷിതമായി ഒപ്പിട്ട് റൂം ഡാറ്റാബേസിൽ ക്യൂ ചെയ്തിരിക്കുന്നു.",

                navHome = "ഹോം",
                navPay = "പേയ്മെന്റ്",
                navActivity = "പ്രവർത്തനം",
                navSecurity = "സുരക്ഷ",
                navSettings = "ക്രമീകരണങ്ങൾ",
                navTerminal = "ടെർമിനൽ",
                navSync = "സമന്വയം",
                navMonitor = "മോണിറ്റർ",
                navAudit = "ഓഡിറ്റ്",
                navRecon = "റീകൺ",

                availableBalance = "ലഭ്യമായ ബാലൻസ്",
                walletBalanceLabel = "പ്രധാന അക്കൗണ്ട് വാലറ്റ്",
                offlineExposure = "ഓഫ്‌ലൈൻ എക്സ്പോഷർ",
                offlineExposureLimit = "പരിധി",
                exposurePercentage = "% ഓഫ്‌ലൈൻ പരിധി ഉപയോഗിച്ചു",
                makePayment = "പണം നൽകുക",
                scanToPay = "സ്കാൻ / ടാപ്പ് ചെയ്യുക",
                forceSync = "ക്ലൗഡ് സിങ്ക് ചെയ്യുക",
                recentTransactions = "സമീപകാല ഇടപാടുകൾ",
                seeAll = "എല്ലാം കാണുക",
                offlineSafeBadge = "ഓഫ്‌ലൈൻ സുരക്ഷിതം",
                cryptographicProofReady = "Ed25519 ഒപ്പിട്ടത്",
                noTransactionsYet = "ഇടപാടുകളൊന്നും കണ്ടെത്തിയില്ല.",

                paymentTitle = "പുതിയ പേയ്മെന്റ്",
                selectMerchant = "വ്യാപാരിയെ തിരഞ്ഞെടുക്കുക",
                enterAmount = "തുക രേഖപ്പെടുത്തുക (₹)",
                quickAmounts = "പെട്ടെന്നുള്ള തുകകൾ",
                paymentMode = "പേയ്മെന്റ് മോഡ്",
                modeAutonomous = "സ്വയംഭരണ (ട്രസ്റ്റ്ഏജന്റ്)",
                modeAutonomousDesc = "റിസ്കും കണക്റ്റിവിറ്റിയും അടിസ്ഥാനമാക്കി അനുയോജ്യമായ മോഡ് തിരഞ്ഞെടുക്കുന്നു",
                modeMandate = "ഓട്ടോപേ മാൻഡേറ്റ്",
                modeMandateDesc = "ബാങ്ക് മാൻഡേറ്റ് ടോക്കൺ വഴിയുള്ള ഡെബിറ്റ് അനുമതി",
                modeOfflineValue = "ഓഫ്‌ലൈൻ മൂല്യം",
                modeOfflineValueDesc = "ക്രിപ്റ്റോഗ്രാഫിക് ഒപ്പോടുകൂടിയ നേരിട്ടുള്ള കൈമാറ്റം",
                trustDecisionTitle = "ട്രസ്റ്റ്ഏജന്റ് തീരുമാനം",
                riskScoreLabel = "റിസ്ക് സാധ്യത",
                confidenceLabel = "വിശ്വാസ്യത",
                tamperSimulation = "സിഗ്നേച്ചർ കൃത്രിമത്വ പരിശോധന (ഡെമോ)",
                tamperActiveWarning = "കൃത്രിമത്വ മോഡ് സജീവമാണ്: നിരസിക്കൽ പരീക്ഷിക്കുന്നതിന് ഒപ്പ് മനഃപൂർവം മാറ്റപ്പെടും.",
                payButton = "ട്രസ്റ്റ്ഏജന്റ് വഴി ₹%s അടയ്ക്കുക",
                signingInstruction = "ഉപകരണത്തിന്റെ പ്രൈവറ്റ് കീ ഒപ്പ് ആവശ്യമാണ്",
                paymentDeclinedTitle = "ഇടപാട് നിരസിച്ചു",
                paymentDeclinedMessage = "റിസ്ക് അല്ലെങ്കിൽ എക്സ്പോഷർ പരിധി കഴിഞ്ഞതിനാൽ ട്രസ്റ്റ്ഏജന്റ് ഈ ഇടപാട് തടഞ്ഞു.",

                paymentSuccessTitle = "ഓഫ്‌ലൈൻ പേയ്മെന്റ് അനുവദിച്ചു",
                paymentSuccessSubtitle = "ഉപകരണ കീ ഉപയോഗിച്ച് ഒപ്പിട്ട് ലോക്കൽ റൂം ഡാറ്റാബേസിൽ സൂക്ഷിച്ചിരിക്കുന്നു.",
                transactionDetails = "ഇടപാട് വിവരങ്ങൾ",
                txId = "ഇടപാട് ഐഡി",
                merchantLabel = "വ്യാപാരി",
                amountPaid = "നൽകിയ തുക",
                modeLabel = "മോഡ്",
                statusLabel = "സ്റ്റാറ്റസ്",
                timestampLabel = "സമയം",
                cryptographicProof = "ക്രിപ്റ്റോഗ്രാഫിക് തെളിവ്",
                publicKeyLabel = "ഉപകരണ പബ്ലിക് കീ",
                signatureLabel = "ഡിജിറ്റൽ സിഗ്നേച്ചർ (Ed25519)",
                nonceLabel = "ആന്റി-റീപ്ലേ നോൺസ്",
                payloadDigest = "കാനോനിക്കൽ ഡൈജസ്റ്റ്",
                syncStatusLabel = "സിങ്ക് സ്റ്റാറ്റസ്",
                queuedInRoom = "റൂമിൽ സൂക്ഷിച്ചിരിക്കുന്നു",
                settledInCloud = "സുപാബേസ് ക്ലൗഡിൽ തീർപ്പാക്കി",
                backToHome = "ഹോമിലേക്ക് മടങ്ങുക",
                triggerCloudSync = "ക്ലൗഡിലേക്ക് ഉടൻ സിങ്ക് ചെയ്യുക",

                terminalTitle = "വ്യാപാരി പിഒഎസ് ടെർമിനൽ",
                merchantBalance = "തീർപ്പാക്കാത്ത രസീതുകൾ",
                todayVolume = "ഇന്നത്തെ ആകെ തുക",
                pendingReconciliation = "ബാക്കിയുള്ള സമന്വയം",
                merchantTransactions = "വന്ന പേയ്മെന്റുകൾ",
                acceptPayment = "സ്വീകരിച്ച് ഒപ്പ് പരിശോധിക്കുക",
                rejectPayment = "നിരസിക്കുക",
                signatureValid = "ഒപ്പ് സാധുവാണ് (Ed25519)",

                adminTitle = "ട്രസ്റ്റ്പേ അഡ്മിൻ മോണിറ്റർ",
                totalVolume = "ആകെ ഇടപാട് തുക",
                totalTransactions = "ആകെ ഇടപാടുകൾ",
                settledTransactions = "തീർപ്പാക്കിയ ഇടപാടുകൾ",
                pendingTransactions = "ബാക്കി സിങ്ക്",
                fraudTransactions = "തട്ടിപ്പ് മുന്നറിയിപ്പുകൾ",
                fraudRate = "തട്ടിപ്പ് നിരക്ക്",
                offlineTxLabel = "ഓഫ്‌ലൈൻ ഇടപാടുകൾ",
                activeAlerts = "സജീവ സുരക്ഷാ മുന്നറിയിപ്പുകൾ",
                viewDetails = "ഫോറൻസിക് വിവരങ്ങൾ കാണുക",

                activityTitle = "സമന്വയ ലെഡ്ജർ",
                syncPipelineTitle = "15-ഘട്ട സമന്വയ പൈപ്പ്‌ലൈൻ",
                syncPipelineSubtitle = "ക്രിപ്റ്റോ പരിശോധന, റീപ്ലേ പരിശോധന, എംഎൽ സ്കോറിംഗ്, റേസർപേ ഗേറ്റ്‌വേ സെറ്റിൽമെന്റ്.",
                startSyncButton = "15-ഘട്ട സിങ്ക് പ്രവർത്തിപ്പിക്കുക",
                allTransactionsHeader = "ഇടപാട് ചരിത്രം",
                filterAll = "എല്ലാം",
                filterPending = "ബാക്കി",
                filterSettled = "തീർപ്പാക്കിയത്",
                filterFlagged = "ഫ്ളാഗ് ചെയ്തത്",

                securityCenterTitle = "ഫോറൻസിക് സുരക്ഷാ കേന്ദ്രം",
                anomalyBreakdown = "എംഎൽ അപാകത സ്കോർ വിവരങ്ങൾ",
                isolationForestScore = "ഐസൊലേഷൻ ഫോറസ്റ്റ് സ്കോർ",
                velocityScore = "ഇടപാട് വേഗത സ്പൈക്ക്",
                exposureRatio = "ഓഫ്‌ലൈൻ എക്സ്പോഷർ അനുപാതം",
                syncDelayScore = "സിങ്ക് കാലതാമസം",
                askGeminiTitle = "ജെമിനി ഫോറൻസിക് വിശദീകരണം",
                askGeminiSubtitle = "ട്രസ്റ്റ്ഏജന്റ് ഇത് എന്തുകൊണ്ട് സ്വീകരിച്ചു അല്ലെങ്കിൽ തടഞ്ഞു എന്ന് ലളിതമായി അറിയുക.",
                askGeminiButton = "ജെമിനിയോട് വിശദീകരണം ചോദിക്കുക",
                restrictAccount = "ഓഫ്‌ലൈൻ ചെലവഴിക്കൽ നിയന്ത്രിക്കുക",
                accountRestricted = "അക്കൗണ്ട് നിയന്ത്രിച്ചിരിക്കുന്നു",
                unrestrictAccount = "നിയന്ത്രണം ഒഴിവാക്കുക",

                settingsTitle = "സിസ്റ്റം ക്രമീകരണങ്ങൾ",
                languageSection = "ആപ്പ് ഭാഷ",
                selectLanguageSubtitle = "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
                themeModeSection = "തീം ക്രമീകരണം",
                selectThemeSubtitle = "ലൈറ്റ്, ഡാർക്ക് അല്ലെങ്കിൽ സിസ്റ്റം ഡിഫോൾട്ട് തിരഞ്ഞെടുക്കുക",
                themeSystem = "സിസ്റ്റം ഡിഫോൾട്ട്",
                themeLight = "ലൈറ്റ്",
                themeDark = "ഡാർക്ക്",
                voiceAssistantSection = "ബഹുഭാഷാ വോയ്‌സ് അസിസ്റ്റന്റ്",
                voiceAssistantSubtitle = "ഇംഗ്ലീഷ്, ഹിന്ദി, കന്നഡ, മലയാളം എന്നിവയിൽ സംസാരിക്കുക",
                launchVoiceAssistant = "വോയ്‌സ് അസിസ്റ്റന്റ് തുറക്കുക",
                activePersona = "സജീവ റോൾ",
                connectionSimulation = "കണക്ഷൻ സിമുലേറ്റർ",
                backendStatus = "ബാക്കെൻഡ് & ക്ലൗഡ് ലെഡ്ജർ",
                hackathonDemoTitle = "ഷോകേസ് ഡെമോ റണ്ണർ",
                hackathonDemoSubtitle = "ഓട്ടോമേറ്റഡ് വെരിഫിക്കേഷൻ പ്രവർത്തിപ്പിക്കുന്നു",
                startDemoButton = "ഡെമോ ആരംഭിക്കുക",
                architecturePrinciples = "പ്രധാന തത്ത്വങ്ങൾ",
                deviceCryptography = "ഉപകരണ ക്രിപ്റ്റോഗ്രഫി & കീകൾ",

                voiceListening = "കേൾക്കുന്നു...",
                voiceTapToSpeak = "സംസാരിക്കാൻ മൈക്ക് തൊടുക",
                voiceTryAsking = "ഇവ ചോദിച്ചു നോക്കൂ:",
                voicePromptBalance = "എന്റെ ബാലൻസ് എത്രയാണ്?",
                voicePromptTransactions = "സമീപകാല ഇടപാടുകൾ കാണിക്കുക",
                voicePromptSync = "സമന്വയം ബാക്കിയുണ്ടോ?",
                voicePromptPay = "ആർട്ടിസാൻ റോസ്റ്റേഴ്സിന് ₹200 അടയ്ക്കുക",
                voicePromptSecurity = "എന്റെ ഓഫ്‌ലൈൻ എക്സ്പോഷർ പരിശോധിക്കുക",
                voicePaymentNotice = "സുരക്ഷയ്ക്കായി, വോയ്‌സ് കമാൻഡുകൾ വഴി നേരിട്ട് പണമടയ്ക്കാൻ കഴിയില്ല. പരിശോധനയ്ക്കായി പേയ്മെന്റ് സ്ക്രീൻ തുറക്കുന്നു.",
                voiceSpeaking = "സംസാരിക്കുന്നു...",
                voiceStopAudio = "ഓഡിയോ നിർത്തുക",
                voicePlayAudio = "ഓഡിയോ കേൾക്കുക",
                voiceClose = "അടയ്ക്കുക",
                voiceNotUnderstood = "ക്ഷമിക്കണം, മനസ്സിലായില്ല. ബാലൻസ്, ഇടപാടുകൾ, സിങ്ക് സ്റ്റാറ്റസ് എന്നിവ ചോദിക്കാം.",

                archRule1 = "മറ്റൊരു കറൻസിയോ ടോക്കണോ സൃഷ്ടിക്കുന്നില്ല",
                archRule2 = "യുപിഐക്ക് പകരമല്ല; റേസർപേ ഓട്ടോപേയുമായി സംയോജിപ്പിച്ചിരിക്കുന്നു",
                archRule3 = "ഓഫ്‌ലൈൻ ഇടപാടുകൾ 'ഓഫ്‌ലൈൻ അംഗീകൃതം' എന്ന് രേഖപ്പെടുത്തുന്നു, തീർപ്പാക്കിയിട്ടില്ല",
                archRule4 = "കൃത്യമായ എക്സ്പോഷർ പരിധികൾ (ഡബിൾ-സ്പെൻഡിന് എഐ ഇല്ല)",
                archRule5 = "Ed25519 ക്രിപ്റ്റോഗ്രാഫിക് സിഗ്നേച്ചർ",
                archRule6 = "ഐസൊലേഷൻ ഫോറസ്റ്റ് & എക്സ്ജിബൂസ്റ്റ് എംഎൽ സ്കോറിംഗ്",
                archRule7 = "ഓഡിറ്റിനായി ജെമിനി എഐ വിശദീകരണം",

                pendingRoomQueue = "ബാക്കിയുള്ള റൂം ക്യൂ",
                lastSyncLabel = "അവസാന സമന്വയം",
                justNow = "ഇപ്പോൾ",
                notSyncedYet = "ഇതുവരെ സമന്വയിപ്പിച്ചിട്ടില്ല",
                razorpayTargetLabel = "റേസർപേ ബാക്കെൻഡ് പ്രോക്സി ടാർഗെറ്റ്",
                renderCloud = "ക്ലൗഡ് റെൻഡർ",
                localEmulator = "ലോക്കൽ എമുലേറ്റർ",
                accountSessionTitle = "അക്കൗണ്ട് സെഷൻ",
                accountSessionDesc = "നിങ്ങളുടെ സെഷൻ അവസാനിപ്പിക്കുക അല്ലെങ്കിൽ മറ്റൊരു ഉപയോക്താവിലേക്ക് മാറുക.",
                logoutButtonLabel = "ലോഗ് ഔട്ട് / അക്കൗണ്ട് മാറുക",

                transactionsDiscoveredLabel = "%d ഇടപാടുകൾ കണ്ടെത്തി",
                signaturesVerifiedLabel = "%d ഒപ്പുകൾ പരിശോധിച്ചു",
                replayAttacksLabel = "%d റീപ്ലേ ആക്രമണങ്ങൾ",
                duplicateTxLabel = "%d ഡ്യൂപ്ലിക്കേറ്റ് ഇടപാടുകൾ",
                highRiskFlaggedLabel = "%d ഉയർന്ന റിസ്ക് ഇടപാട് തടഞ്ഞു",
                lowRiskTxLabel = "%d കുറഞ്ഞ റിസ്ക് ഇടപാടുകൾ",
                settlementSummaryTitle = "സെറ്റിൽമെന്റ് സംഗ്രഹം",
                settlementSummaryDesc = "%d വിജയിച്ചു, %d പരിശോധന ആവശ്യമാണ്",
                reviewFlaggedItemButton = "തടഞ്ഞ ഇടപാട് പരിശോധിക്കുക ->",

                anomalyInvestigationTitle = "അപാകത പരിശോധന",
                riskSpectrumTitle = "റിസ്ക് സാധ്യത വിവരങ്ങൾ",
                riskSpectrumLow = "0% (കുറഞ്ഞത്)",
                riskSpectrumMedium = "50% (ഇടത്തരം)",
                riskSpectrumCritical = "100% (ഗുരുതരം)",
                dualRiskAnalysisTitle = "ഇരട്ട റിസ്ക് വിശകലന സംവിധാനം",
                ruleBasedScoreTitle = "നിയമാധിഷ്ഠിത റിസ്ക് സ്കോർ",
                ruleBasedScoreSubtitle = "ലോക്കൽ എഞ്ചിൻ (FraudDetector.kt)",
                mlModelScoreTitle = "എംഎൽ മോഡൽ റിസ്ക് സ്കോർ",
                mlModelScoreSubtitle = "പരിശീലനം ലഭിച്ച എക്സ്ജിബൂസ്റ്റ് മോഡൽ വഴി പരിശോധിച്ചു",
                evaluatingText = "പരിശോധിക്കുന്നു...",
                mlServiceUnavailable = "എംഎൽ സേവനം ലഭ്യമല്ല — ലോക്കൽ നിയമങ്ങൾ ഉപയോഗിക്കുന്നു",
                mlFallbackNotice = "സർവർ ലഭ്യമായിരുന്നില്ല. സത്യസന്ധമായ ഫോൾബാക്ക് സജീവമാണ്.",
                retryMlServiceButton = "എംഎൽ സേവനം വീണ്ടും ശ്രമിക്കുക",
                whyFlaggedTitle = "എന്തുകൊണ്ട് തടയപ്പെട്ടു",
                investigateWithGeminiTitle = "ജെമിനി എഐ ഉപയോഗിച്ച് പരിശോധിക്കുക",
                geminiModelSubtitle = "മോഡൽ: gemini-2.5-flash • വിശദീകരണം മാത്രം",
                suggestedQuestionsTitle = "നിർദ്ദേശിച്ച ചോദ്യങ്ങൾ:",
                qWhyFlagged = "എന്തുകൊണ്ടാണ് ഇത് തടഞ്ഞത്?",
                qIsDeviceCompromised = "ഉപകരണം സുരക്ഷിതമാണോ?",
                qRecommendedActions = "ശിപാർശ ചെയ്യുന്ന നടപടികൾ",

                enterAmountOnlineDesc = "റേസർപേ വഴി അയയ്ക്കാൻ തുക നൽകുക",
                enterAmountOfflineDesc = "%s വഴി അയയ്ക്കാൻ തുക നൽകുക"
            )

        }
    }
}

val LocalAppStrings = compositionLocalOf { AppStrings() }
val LocalAppLanguage = compositionLocalOf { AppLanguage.ENGLISH }
